<?php 
Wo_UpdateSeenReports();
?>
<div class="list-group setting-reports-container">
   <div class="list-group-item"><i class="fa fa-fw fa-pencil"></i> <?php echo $wo['lang']['manage_posts']; ?></div>
   <div class="setting-well">
     <div class="table-responsive">
      <table class="table table-hover table-bordered table-stripped setting-table">
         <thead>
            <tr>
               <th><?php echo $wo['lang']['id'];?></th>
               <th><?php echo $wo['lang']['type'];?> </th>
               <th><?php echo $wo['lang']['reporter'];?> </th>
               <th>Link</th>
               <th><?php echo $wo['lang']['time_reported'];?> </th>
               <th><?php echo $wo['lang']['action'];?></th>
            </tr>
         </thead>
         <tbody class="result">
            <?php 
               $reports = Wo_GetReports();
               if (count($reports) > 0) {
                 foreach ($reports as $wo['report']) {
                    echo Wo_LoadPage('admin/manage_reports/reports-list');
                 }
               } 
               ?>
         </tbody>
      </table>
      </div>
   </div>
</div>
<div class="modal fade" id="read_report" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> View report</h4>
         </div>
         <div class="modal-body">
            <p class="report_text"></p>
         </div>
         <div class="modal-footer">
            <button  type="button" class="btn btn-default" data-dismiss="modal"><?php echo $wo['lang']['close']; ?></button>
         </div>
      </div>
   </div>
</div>
<script>
$(function () {
  $('table').DataTable({"aoColumnDefs": [
          { 'bSortable': false, 'aTargets': [ 5 ] }
    ],
   "order": [[ 0, "desc" ]]});
});
function Wo_DeleteReportedContent(id,report_id,type  = '') {
  if (confirm("With the confirmation, the content will be deleted?") == false || !type) {
    return false;
  }
  var no_reports_container = $('.setting-reports-container').find('.no-result');
  var delete_icon = $('.setting-reports-container').find('#ReportID_' + report_id).find('.delete-report');
  Wo_progressIconLoader(delete_icon);
  $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s:'delete_reported_content', id:id, report_id:report_id,type:type}, function(data) {
    if (data.status == 200) {
      $('#ReportID_' + report_id).fadeOut(300, function() {
        $(this).remove();
      });
      if (data.html == 0) {
        no_reports_container.hide().html('<span class="center-text"><?php echo $wo["lang"]["there_are_no_new_reports"]?></span>').fadeIn(300);
        $('#manage-reports-tab').find('.new-update-alert').fadeOut(200);
      } else {
        $('#manage-reports-tab').find('.new-update-alert').text(data.html);
      }  
    }
  });
}

function Wo_MarkSafeReportedPost(report_id) {
    var no_reports_container = $('.setting-reports-container').find('.no-result');
    var safe_icon = $('.setting-reports-container').find('#ReportID_' + report_id).find('.mark-safe');
    Wo_progressIconLoader(safe_icon);
    $.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s:'mark_as_safe', report_id:report_id}, function(data) {
      if (data.status == 200) {
        $('#ReportID_' + report_id).fadeOut(300, function() {
          $(this).remove();
        });
        if (data.html == 0) {
         	no_reports_container.hide().html('<span class="center-text"><?php echo $wo["lang"]["there_are_no_new_reports"]?></span>').fadeIn(300);
          $('#manage-reports-tab').find('.new-update-alert').fadeOut(200);
        } else {
            $('#manage-reports-tab').find('.new-update-alert').text(data.html);
        }
      }
    });
}
</script>