<?php echo Wo_LoadPage('ads/includes/header'); ?>

<div class="ads-cont-wrapper">
	<table class="table table-striped">
		<thead>
		  <tr>
		    <th>
		    	<?php echo $wo['lang']['id']; ?>
		    </th>
		    <th><?php echo $wo['lang']['company']; ?></th>
		    <th><?php echo $wo['lang']['bidding']; ?></th>
		    <th><?php echo $wo['lang']['clicks']; ?></th>
		    <th>
		    	<?php echo $wo['lang']['views']; ?>
		    </th>
		    <th><?php echo $wo['lang']['status']; ?></th>
		    <th><?php echo $wo['lang']['action']; ?></th>
		  </tr>
		</thead>
		<tbody id="user-ads">
		<?php if (count($wo['ads']) > 0): ?>
		  <?php foreach ($wo['ads'] as $wo['ad']): ?>
		  	<?php echo Wo_LoadPage('ads/includes/ads-list');?>
		  <?php endforeach; ?>
		<?php else: ?>
			<tr>
				<td colspan="7" class="text-center" style="height: 200px;">
					<?php echo $wo['lang']['no_ads_found']; ?>
				</td>
			</tr>
		<?php endif; ?>
		</tbody>
	</table>
</div>

<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
 	<div class="posts_load">
	    <?php if (count($wo['ads']) > 0): ?>
		<div class="load-more">
            <button class="btn btn-default text-center pointer load-more-ads">
            <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i>
            <?php echo $wo['lang']['load_more'] ?>
            </button>
        </div>
        <?php endif ?>
	</div>
</div>

<div class="modal fade" id="delete-ad" >
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> <?php echo $wo['lang']['delete_ad']; ?></h4>
         </div>
         <div class="modal-body">
            <p><?php echo $wo['lang']['confirm_delete_ad']; ?></p>
         </div>
         <div class="modal-footer">
            <button  type="button" onclick="Wo_DeleteAd($('#delete-ad').attr('data-userad-id'))" class="btn  btn-main"><i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> <?php echo $wo['lang']['delete']; ?></button>
            <button  type="button" class="btn btn-default" data-dismiss="modal"><?php echo $wo['lang']['cancel']; ?></button>
         </div>
      </div>
   </div>
</div>

<script>
	
	jQuery(document).ready(function($) {
		$(document).on('click', '.delete-ad', function(event) {
			var self = $(this);	
			$("#delete-ad").attr('data-userad-id',self.attr('id')).modal("show");

		});

		$(document).on('click', '.toggle-user-ad-status', function(event) {
			var self      = $(this);
			var ad_id     = self.attr('id');
			var ad_status = self.attr('data-status');
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'ads',s:'ts',ad_id:ad_id,status:ad_status},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("[data-ad-status='"+ad_id+"']").find('span').text(data.ad);
					if (ad_status == 0) {
						self.html('<i class="fa fa-times-circle-o"></i>');
						self.attr('data-status',1);
					}
					else{
						self.html('<i class="fa fa-check-circle-o"></i>');
						self.attr('data-status',0);
					}
				}
			})
			.fail(function() {
				console.log("error");
			})
		
		});

		$(".load-more-ads").click(function(event) {
			var last_ad = ($("tr[data-ad-id]").length > 0) ? $("tr[data-ad-id]").last().attr('data-ad-id') : 0;
			var self    = $(this);
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'ads',s:'lm',ad_id:last_ad},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("#user-ads").append(data.html);
				}
				else if(data.status == 404){
					self.removeClass('load-more-ads').html(data.html);
				}
				else{
					self.remove();
				}
			})
			.fail(function() {
				console.log("error");
			})
			
		});
	});

	function Wo_DeleteAd(id){
		if (id && id > 0) {
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'wallet',s:'remove',id:id},
			})
			.done(function(data) {
				if (data.status == 200) {
					$("tr[data-ad-id="+id+"]").slideUp(function(){
						$(this).remove();
					})
					$("#delete-ad").modal("hide");
				}
			})
			.fail(function() {
				console.log("error");
			})
		}
	}
</script>

