<div class="page-margin">
   <div class="row">
   <div class="col-md-2"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
    <div class="col-md-7 no-padding-right">
    	<?php if (Wo_IsAdmin() && strpos($wo['config']['site_url'], 'https') === false): ?>
    		<div class="alert alert-warning">
    			<p><i class="fa fa-info-circle"></i> SSL is required to able to use this feature. (Just admin can see this warning) </p>
    		</div>
    	<?php endif; ?>
      	<div class="list-group-item search-nearby-users-form">
			<form action="#">
				<div class="inner-addon left-addon">
				    <i class="glyphicon fa fa-search progress-icon" aria-hidden="true"></i>
					<input type="text" class="form-control" placeholder="<?php echo $wo['lang']['find_friends_nearby']; ?>" id="nearby-username">
				</div>
			</form>
		</div>
		<br>
         <div class="list-group">
            <div class="list-group-item find_friends_nearby_head">
               <?php echo $wo['lang']['people_you_may_know'];?>
               <div class="clear"></div>
            </div>
            <div class="setting- nearby_users_cont">
            	<div id="nearby_users_list">
            		<?php
                 		$nearby_users = Wo_GetNearbyUsers(array('country' => $wo['user']['country_id']));
                 		if (count($nearby_users) > 0) {
                 			foreach ($nearby_users as $wo['UsersList']) {
	                          echo Wo_LoadPage('friends_nearby/includes/user-list');
	                        }
                 		}
                 		else{
                 			echo '<h5 class="search-filter-center-text"> ' . $wo['lang']['no_users_found'] . '</h5>';
                 		}
                        
                   
                    ?>
                    
            	</div>
            	
	            <div class="clear"></div>
            </div>
         </div>
         <div class="posts_load">
           <?php if (count($nearby_users) >= 1): ?>
              <div class="load-more">
                    <div class="btn btn-default text-center pointer" id="load_more_nearby_users" onclick="Wo_LoadMoreNearByUsers();">
                      <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> 
                      <?php echo $wo['lang']['load_more'] ?>
                    </div>
              </div>
           <?php endif ?>
	    </div>
    </div>

    <div class="col-md-3">
       <div  id="search-nearby-users">
          <div class="nearby-users-gender"><?php echo $wo['lang']['gender'];?></div>
          <div class="nearby-users-gender-collapse nearby-users-gender-cont">
	          <ul>
	          	<li class="active" data-gender="all"><?php echo $wo['lang']['all'];?></li>
	          	<li data-gender="male"><?php echo $wo['lang']['male'];?></li>
	          	<li data-gender="female"><?php echo $wo['lang']['female'];?></li>
	          </ul>
          </div>
          <div class="nearby-users-distance"><?php echo $wo['lang']['location_dist'];?></div>
          <div class="select-nearby-users-distance">
	         <input type="number" class="form-control" placeholder="<?php echo $wo['lang']['distance_from_u'];?>" id="nearby-users-distance" onchange="Wo_LoadNearByUsers();" min="1" max="40000">
          </div>
          <div class="nearby-users-gender nearby-users-relationship"><?php echo $wo['lang']['relationship']; ?></div>
          <div class="nearby-users-gender-collapse nearby-users-relationship-collapse">
	          <ul>
	          	<li class="active" data-relation-ship="5"><?php echo $wo['lang']['all'];?></li>
	            <?php foreach ($wo['relationship'] as $relationship_ids => $relationship): ?>
	            	<li class="" data-relation-ship="<?php echo $relationship_ids; ?>"><?php echo $relationship;?></li>
	            <?php endforeach; ?>
	          </ul>
          </div>
          <div class="nearby-users-gender nearby-users-status"><?php echo $wo['lang']['status']; ?></div>
          <div class="nearby-users-gender-collapse nearby-users-status-collapse">
	          <ul>
	            <li class="active" data-nearby-user-status="2"><?php echo $wo['lang']['all'];?></li>
	            <li  data-nearby-user-status="1"><?php echo $wo['lang']['online'];?></li>
	            <li  data-nearby-user-status="0"><?php echo $wo['lang']['offline'];?></li>
	          </ul>
          </div>
          <div class="search-nearby-users-btn">
	          <button type="button" class="btn btn-main form-control" onclick="Wo_LoadNearByUsers(this);">
	          	<i class="fa fa-search progress-icon" data-icon="search"></i>
	          	<?php echo $wo['lang']['search']; ?>
	          </button>
          </div>

       </div>
       <?php echo Wo_LoadPage('footer/sidebar-footer')?>
       <div class="clear"></div>
    </div>
   </div>
   <!-- .row -->
</div>
<div class="modal" id="show_user_location_map" role="dialog">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
         <div class="modal-body">
            <iframe src="" frameborder="0" width="100%" style="height: calc(100vh - 300px);"></iframe>
         </div>
         <div class="modal-footer">
         <button type="button" class="btn btn-default" data-dismiss="modal" onclick="javascript:$('#show_user_location_map').modal('hide');">
         <?php echo $wo['lang']['close']; ?>
         </button>
         </div>
      </div>
   </div>
</div>
<script>
	function Wo_ShowUserLocationMap(user_geoData = false) {
		if (!user_geoData) {return false;}
		var google_map_api = 'https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + user_geoData;
		$("#show_user_location_map").modal().find('iframe').attr('src', google_map_api);

	}
	function Wo_LoadNearByUsers(self = false){
		var relship  = $(".nearby-users-relationship-collapse").find('.active').attr('data-relation-ship');
		var status   = $(".nearby-users-status-collapse").find('.active').attr('data-nearby-user-status');
		var gender   = $(".nearby-users-gender-cont").find('.active').attr('data-gender');
		var name     = $("#nearby-username").val();
		var distance = $("#nearby-users-distance").val();
		if (!gender && !name && !distance && !relship && !status) { return false;}
		if (self) {
			Wo_progressIconLoader($(self));
		}
		else{
			Wo_StartBar();
		}
		
		$.ajax({
			url: Wo_Ajax_Requests_File(),
			type: 'GET',
			dataType: 'json',
			data: {
				f:'nearby_users',
				s:'load',
				gender:gender,
				name:name,
				distance:distance,
				status:status,
				relship:relship
			},
		})
		.done(function(data) {

	        if (data['status'] == 200){
	        	$("#nearby_users_list").html(data.html);
	        	$("[data-toggle]").tooltip();
	        	$("#load_more_nearby_users").html('<i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more']; ?>');
	        } 

	        else{
	        	scrollToTop();
	        	$("#nearby_users_list").html('<h5 class="search-filter-center-text"> <?php echo $wo['lang']['no_users_found']; ?></h5>');
	        } 
	        if (self) {
				Wo_progressIconLoader($(self));
			}
			else{
				Wo_FinishBar();
			}
		})
		.fail(function() {
			console.log("error");
		})
		
		
		
	}
	function Wo_LoadMoreNearByUsers(){
		var relship  = $(".nearby-users-relationship-collapse").find('.active').attr('data-relation-ship');
		var status   = $(".nearby-users-status-collapse").find('.active').attr('data-nearby-user-status');
		var after_id = ($(".nearby_user_wrapper").length > 0) ? $(".nearby_user_wrapper").last().attr('id') : 0;
		var gender   = $(".nearby-users-gender-cont").find('.active').attr('data-gender');
		var name     = $("#nearby-username").val();
		var distance = $("#nearby-users-distance").val();
		if (!after_id && !gender && !name && !distance && !status && !relship) { return false;}
		Wo_progressIconLoader($('#load_more_nearby_users'));
		$.ajax({
			url: Wo_Ajax_Requests_File(),
			type: 'GET',
			dataType: 'json',
			data: {
				f:'nearby_users',
				s:'load',
				offset:after_id,
				gender:gender,
				name:name,
				distance:distance,
				relship:relship,
				status:status

			},
		})
		.done(function(data) {

	        if (data['status'] == 200){
	        	$("#nearby_users_list").append(data.html);
	        	$("[data-toggle]").tooltip();
	        	$("#load_more_nearby_users").html('<i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more']; ?>');
	        } 

	        else{
	        	$("#load_more_nearby_users").html('<?php echo $wo['lang']['no_result']; ?>');
	        } 
		})
		.fail(function() {
			console.log("error");
		})
		
	}

	jQuery(document).ready(function($) {
		$("[data-gender]").click(function(event) {
			$(".nearby-users-gender-cont").find('.active').removeClass('active');
			$(this).addClass('active');
			Wo_LoadNearByUsers();
		});
		$("[data-relation-ship]").click(function(event) {
			$(".nearby-users-relationship-collapse").find('.active').removeClass('active');
			$(this).addClass('active');
			Wo_LoadNearByUsers();
			
		});
		$("[data-nearby-user-status]").click(function(event) {
			$(".nearby-users-status-collapse").find('.active').removeClass('active');
			$(this).addClass('active');
			Wo_LoadNearByUsers();
		});
	});
</script>

