<div class="container-fluid">
    <div class="block-header">
        <h2>Manage Features > Groups</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
          <div class="col-lg-3 col-md-3">
            <div class="info-box bg-orange  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">people</i>
                </div>
                <div class="content">
                    <div class="text">TOTAL GROUPS</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllData('group'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 ">
            <div class="info-box bg-orange  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">people_outline</i>
                </div>
                <div class="content">
                    <div class="text">JOINED GROUPS</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountGroupData('members'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 ">
            <div class="info-box bg-orange  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">mode_edit</i>
                </div>
                <div class="content">
                    <div class="text">TOTAL POSTS</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountGroupData('groups_posts'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 ">
            <div class="info-box bg-orange  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">library_add</i>
                </div>
                <div class="content">
                    <div class="text">JOIN REQUESTS</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountGroupData('join_requests'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage & Edit Groups</h2>
                </div>
                <div class="body">
                   <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                      <th>ID</th>
					                  <th>Group Name</th>
					                  <th>Owner</th>
					                  <th>Category</th>
                            <th>Memebers</th>
					                  <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               <?php 
				               foreach (Wo_GetAllGroups(20) as $wo['grouplist']) {
				                  echo Wo_LoadAdminPage('manage-groups/list');
				                }
				               ?>
                            </tbody>
                        </table>
                        <div class="text-center">
                             <button onclick="Wo_GetMoreGroups();" type="button" class="btn btn-default btn-load-more waves-effect btn-lang">Load More Groups</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

function Wo_GetMoreGroups() {
  after_group_id = $('.setting-grouplist:last').attr('data-group-id');
 $('.btn-load-more').text('Please wait..');
  $.get(Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_more_groups', {after_group_id: after_group_id}, function(data) {
    if (data.html.length != 0) {
      $('tbody').append(data.html);
      $('.btn-load-more').text('Load More Groups');
    } else {
      $('.btn-load-more').text('No More Groups');
    }
  });
}

function Wo_DeleteGroup(group_id) {
  if (confirm("Are you sure you want to delete this group?") == false) {
    return false;
  }
  hash_id = $('#hash_id').val();
  $('#GroupID_' + group_id).fadeOut(300, function() {
    $(this).remove();
  });
  $.get(Wo_Ajax_Requests_File(),{f:'admin_setting',s:'delete_group',group_id: group_id, hash_id:hash_id});
}
</script>