<li>
	<div class="user-avatar" data-toggle="tooltip" title="<?php echo $wo['user_status']['user_data']['name']?>" data-placement="bottom">
		<a href="<?php echo $wo['user_status']['user_data']['url'] . $wo['marker'];?>story=true" data-ajax="?link1=timeline&u=<?php echo $wo['user_status']['user_data']['username'];?>&story=true"><img src="<?php echo $wo['user_status']['thumb']['filename'];?>" ></a> 
	</div>	
</li>