<div class="container-fluid">
    <div class="block-header">
        <h2>Manage Features > Posts</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
          <div class="col-lg-3 col-md-3">
            <div class="info-box bg-cyan  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">comment</i>
                </div>
                <div class="content">
                    <div class="text">TOTAL COMMENTS</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountAllData('comments'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 ">
            <div class="info-box bg-cyan  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">thumb_up</i>
                </div>
                <div class="content">
                    <div class="text">TOTAL LIKES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountPostData('likes'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 ">
            <div class="info-box bg-cyan  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">error</i>
                </div>
                <div class="content">
                    <div class="text">TOTAL WONDERS / DISLIKES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountPostData('wonders'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 ">
            <div class="info-box bg-cyan  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">reply</i>
                </div>
                <div class="content">
                    <div class="text">TOTAL REPLIES</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo Wo_CountPostData('replies'); ?>" data-speed="1000" data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
        
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage & Edit Posts</h2>
                </div>
                <div class="body">
                   <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                      <th>ID</th>
					                  <th>Publisher</th>
					                  <th>Post Link</th>
					                  <th>Posted</th>
					                  <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               <?php 
				               foreach (Wo_GetAllPosts() as $wo['story']) {
				                  echo Wo_LoadAdminPage('manage-posts/list');
				                }
				               ?>
                            </tbody>
                        </table>
                        <div class="text-center">
                             <button onclick="Wo_AdminGetMorePosts();" type="button" class="btn btn-default btn-load-more waves-effect btn-lang">Load More Posts</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
function Wo_AdminDeletePost(post_id) {
    if (confirm("Are you sure you want to delete this post?") == false) {
      return false;
    }
    hash_id = $('#hash_id').val();
    $('#PostID_' + post_id).fadeOut(300, function() {
       $(this).remove();
    });
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_post', {post_id:post_id, hash_id:hash_id});
}

function Wo_AdminGetMorePosts() {
    after_post_id = $('.setting-postlist:last').attr('data-post-id');
    $('.btn-load-more').text('Please wait..');
    $.get(Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_more_posts', {after_post_id:after_post_id}, function(data) {
      if (data.html.length != 0) {
        $('tbody').append(data.html);
        $('.btn-load-more').text('Load More Posts');
      } else {
        $('.btn-load-more').text('No More Posts');
      }
    });
}
</script>