<?php echo Wo_LoadPage('ads/includes/header'); ?>


<div class="list-group">
  <br>
  <?php if (isset($wo['replenishment_notif'])): ?>
    <div class="col-md-12" id="replenish-user-account-alert">
      <div class="alert alert-success">
        <i class="fa fa-check" aria-hidden="true"></i>
        <?php echo $wo['replenishment_notif'];?> 
        
      </div>
    </div>
  <?php else: ?>
    <div class="col-md-12" id="replenish-user-account-alert">
      
    </div>
  <?php endif; ?>
  <br>
  <div class="col-md-8"> 
    <form class="form" id="replenish-user-account">

    	<div class="form-group w100">
    		<label class="col-md-3"><?php echo $wo['lang']['my_balance'];?></label>
  		<div class="col-md-9">
  			<h5>
  					 <?php echo Wo_GetCurrency($wo['config']['ads_currency']) ?><?php echo $wo['user']['wallet'];?>
  			</h5>
  		</div>
    	</div>
      

    	<div class="w100">
    		<label class="col-md-3"></label>
  		<div class="col-md-9 main"><small><?php echo $wo['lang']['replenish_my_balance'];?></small></div>
    	</div>

    	<div class="form-group w100 add-amount">
    		<label class="col-md-3">
          <?php echo $wo['lang']['amount'];?>
        </label>
    		<div class="col-md-9">
    			<input type="number" class="form-control" placeholder="0.00" min="1.00" max="1000"  name="amount" id="amount">
    		</div>
    	</div>
    	<div class="form-group w100">
    		<label class="col-md-3"></label>
    		<div class="col-md-9">
    			<button type="submit" class="btn btn-main">
            <i class="fa progress-icon"></i>
    				<?php echo $wo['lang']['continue'];?>
    			</button>
    		</div>
    	</div>
    </form>
  </div> 
</div>

<script>
	jQuery(document).ready(function($) {
		$('#replenish-user-account').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=wallet&s=replenish-user-account',
            beforeSend: function() {
              Wo_progressIconLoader($('#replenish-user-account').find('button'));
            },
            success: function(data) {
              scrollToTop();
              if (data['status'] == 200 && data['type'] == 'SUCCESS') {
                window.location = data['url'];
              }
              else if(data['status'] == 500){
              	$("#replenish-user-account-alert").html('<div class="alert alert-danger">' + data['error'] + '</div>');
              }
              else{
                $("#replenish-user-account-alert").html('<div class="alert alert-danger">' + data['details']['error_description'] + '</div>');
                }
              Wo_progressIconLoader($('#replenish-user-account').find('button')); 
            }
        });
	});
</script>