<style>
    .wel_title{
 color: #c45a5b;
    font-size: 22px;
    font-weight: bold;
    font-family: cursive;   

}
.welcome{
     font-size: 14px;
    line-height: 22px;
    font-weight: bold;
}
</style>
<div class="posts-container list-group">
   <div class="no-posts">
      <span class="wel_title" style="color:#c45a5b;"> Welcome to Mitrah The Indian Social Networking Website.</span>
      <?php// echo $wo['lang']['welcome_to_news_feed'];?>
      <h1><i class="fa fa-pencil-square-o"></i></h1>
      <?php// echo $wo['lang']['say_hello'];?>
      <p class="welcome">As everybody knows that all social networking website like Facebook keep our data and sell it to make money. So we have come up with the website which guarantee the security of your data and make promise that it will not be used to make money.</p>

<p  class="welcome">So please stop sharing your birthday, life events , photo, video and location to Facebook and twitter and start using India's Social networking website which is 100% safe and secure.</p>
   </div>
</div>    