<div id="film-alert">

</div>
<form id="new-film">
	<div class="form-group">
		<label for="name" class="col-md-2 col-sm-12 col-xs-12">
			Movie title
		</label>
		<div class="col-md-9 col-ms-9 col-xs-9">
			<input type="text" name="name" class="form-control">
		</div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
		<label for="name" class="col-md-2 col-sm-12 col-xs-12">
			Genre
		</label>
		<div class="col-md-4 col-ms-9 col-xs-9">
			<select name="genre" class="form-control">
				<?php foreach ($wo['film-genres'] as $g_key => $g_value): ?>
					<option value="<?php echo $g_key; ?>"><?php echo $g_value; ?></option>
				<?php endforeach;?>
				
			</select>
		</div>
		<div class="col-md-4" id="select-film">
           <input type="file" name="source" id="film" accept="video/*" value="C:\fakepath\source">
        </div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
		<label for="youtube" class="col-md-2 col-sm-12 col-xs-12">
			Source
		</label>
		<div class="col-md-9 col-ms-9 col-xs-9">
			<input id="embed_source" class="form-control" name="iframe" type="url" onchange="Wo_ToggleMoviewsSource(this)" placeholder="Example: (youtube.com,vimeo.com,site.com/video.mp4)">
			<div class="preview-utube-import hidden" style="margin-top: 25px;">
				<iframe width="100%" height="350px" src="" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
		<label for="name" class="col-md-2 col-sm-12 col-xs-12">
			Stars
		</label>
		<div class="col-md-9 col-ms-9 col-xs-9">
			<textarea class="form-control" name="stars"></textarea>
		</div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
		<label for="name" class="col-md-2 col-sm-12 col-xs-12">
			Producer
		</label>
		<div class="col-md-9 col-ms-9 col-xs-9">
			<input type="text" class="form-control" name="producer">
		</div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
		<label for="name" class="col-md-2 col-sm-12 col-xs-12">
			Country
		</label>
		<div class="col-md-4 col-ms-9 col-xs-9">
			<select name="country" class="form-control">
				<?php foreach ($wo['countries'] as $c_key => $c_value): ?>
					<option value="<?php echo $c_key; ?>"><?php echo $c_value; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div class="col-md-4 col-ms-9 col-xs-9">
			<select name="quanlity" class="form-control">
				<option value="cam">CAMRip</option>
				<option value="ts">TS</option>
				<option value="vsh">VHSRip</option>
				<option value="wp">WP</option>
				<option value="scr">SCR (VHSScr)</option>
				<option value="dvds">DVDScr</option>
				<option value="ts">TC</option>
				<option value="ldr">LDRip</option>
				<option value="tv">TVRip</option>
				<option value="sat">SATRip</option>
				<option value="dvb">DVBRip</option>
				<option value="dtv">DTVRip</option>
				<option value="dvd">DVD</option>
				<option value="hdr">HDRip</option>
				<option value="web-dl">WEB-DL</option>
				<option value="hd-tv">HD-TV</option>
				<option value="hd">HD DVD</option>
			</select>
		</div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
		
		<label for="name" class="col-md-2 col-sm-12 col-xs-12">
			Release
		</label>
		<div class="col-md-4 col-ms-9 col-xs-9" >
			<input type="number" class="form-control"  min="1980" max="<?php echo date('Y'); ?>" step="1" placeholder="<?php echo date('Y'); ?>" name="release">
		</div>
		<div class="col-md-4 col-ms-9 col-xs-9">
			<input type="number" class="form-control" name="duration"  min="10"  max="350" placeholder="Duration">
		</div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
		
		<label for="name" class="col-md-2 col-sm-12 col-xs-12">
			Description
		</label>
		<div class="col-md-9 col-ms-9 col-xs-9" >
			<textarea name="description" class="form-control" rows="5"></textarea>
		</div>
		<div class="clear"></div>
	</div>
	<div class="form-group">
        <label class="col-md-2" for="new-blog-desc" title="Upload"  class="pointer"><?php echo $wo['lang']['cover'] ?></label>  
        <div class="col-md-9 main pointer" id="select-f-cover">
           <label><i class="fa fa-camera fa-wh" aria-hidden="true"></i> <?php echo $wo['lang']['select'] ?></label>
        </div>
        <div class="clear"></div>
    </div>

    <br>
    <div class="publisher-hidden-option">
         <div id="progress">
            <span id="percent">0%</span>
            <div class="progress">
             <div id="bar" class="progress-bar progress-bar-striped active"></div> 
            </div>
            <div class="clear"></div>
         </div>
      </div>
   	<div class="form-group" id="upload-film">
		<label for="name" class="col-md-2"></label>
		<div class="col-md-9">
			<button type="submit" class="btn btn-main">
           		<i class="fa fa-cloud-upload progress-icon" aria-hidden="true" data-icon="cloud-upload"></i> <?php echo $wo['lang']['upload'] ?>
           </button>
		</div>
		<div class="clear"></div>
	</div>
	<input type="file" class="hidden" name="cover" id="film-cover" accept="image/*">
</form>

<script>
	function Wo_IsURL(str) {
	  var pattern = new RegExp('^(https?:\\/\\/)?'+ 
	  '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.?)+[a-z]{2,}|'+ 
	  '((\\d{1,3}\\.){3}\\d{1,3}))'+ 
	  '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*'+ 
	  '(\\?[;&a-z\\d%_.~+=-]*)?'+ 
	  '(\\#[-a-z\\d_]*)?$','i'); 
	  return pattern.test(str);
	}

	function Wo_FilmMediaUrl(pastedData) {
		var success = false;
		var media   = {};
		if (GetYoutubeId(pastedData)) {

		    media.type  = "youtube";
		    media.id    = GetYoutubeId(pastedData);
		    success     = true;
		    $("#embed_source").attr('name', 'iframe');
		}
		else if (Wo_GetVimeoID(pastedData)) {
		    media.type  = "vimeo";
		    media.id    = Wo_GetVimeoID(pastedData);
		    success     = true;
		    $("#embed_source").attr('name', 'iframe');
		}
		else if (Wo_GetVideopressId(pastedData)) {
		    media.type  = "videopress";
		    media.id    = Wo_GetVideopressId(pastedData);
		    success     = true;
		    $("#embed_source").attr('name', 'iframe');
		}
		else if (Wo_IsURL(pastedData)) {
			alert(Wo_IsURL(pastedData))
		    media.type  = "other";
		    media.id    = pastedData;
		    success     = true;
		    $("#embed_source").attr('name', 'other');
		    alert(pastedData)

		}
		if (success) { return media; }
		else { alert("Not valid source id detected"); }
		return false;
	}
	function  Wo_ToggleMoviewsSource(self = false) {
		if (!self || self.value.length == '') {
			$('#film').attr('disabled', false);
			return false;
		}
		$('#film').attr('disabled', true);
		var url_data = Wo_FilmMediaUrl(self.value);
		if (url_data && url_data.type == 'youtube') {
			var u_source = "https://www.youtube.com/embed/" + url_data.id;
			$(".preview-utube-import").removeClass('hidden').find('iframe').attr('src', u_source);
			self.value = u_source;
		}
		else if (url_data && url_data.type == 'vimeo') {
			var u_source = "https://player.vimeo.com/video/" + url_data.id;
			alert(u_source)
			$(".preview-utube-import").removeClass('hidden').find('iframe').attr('src', u_source);
			self.value   = u_source;
		}
		else if (url_data && url_data.type == 'other') {
			var u_source = url_data.id;
			var html = "\
			<div class='video-js-responsive-container vjs-hd'>\
			<video onplay='' class='video-js vjs-big-play-centered' controls preload='auto' poster='' data-setup='{}'>\
			    <source src='"+u_source+"' type='video/mp4'>\
			    <source src='"+u_source+"' type='video/webm'>\
			</video>\
			<script src='<?php echo $wo['config']['theme_url'];?>/player/Video/video.js'><\/script>\
			</div>\ ";
			$(".preview-utube-import").removeClass('hidden').html(html);
			self.value = u_source;
		}
	}


	function Wo_GetVimeoID(str) {
		if (str.indexOf('#') > -1) {
			str = str.split('#')[0];
		}
		if (str.indexOf('?') > -1) {
			str = str.split('?')[0];
		}

		var id;
		if (/https?:\/\/vimeo\.com\/[0-9]+$|https?:\/\/player\.vimeo\.com\/video\/[0-9]+$/igm.test(str)) {
			var arr = str.split('/');
			if (arr && arr.length) {
				id = arr.pop();
			}
		}
		return id;
	}




	function GetYoutubeId(str) {
		var shortcode = /youtube:\/\/|https?:\/\/youtu\.be\//g;

		if (shortcode.test(str)) {
			var shortcodeid = str.split(shortcode)[1];
			return Wo_StripParameters(shortcodeid);
		}
		var inlinev = /\/v\/|\/vi\//g;

		if (inlinev.test(str)) {
			var inlineid = str.split(inlinev)[1];
			return Wo_StripParameters(inlineid);
		}
		var parameterv = /v=|vi=/g;

		if (parameterv.test(str)) {
			var arr = str.split(parameterv);
			return arr[1].split('&')[0];
		}

		var embedreg = /\/embed\//g;

		if (embedreg.test(str)) {
			var embedid = str.split(embedreg)[1];
			return Wo_StripParameters(embedid);
		}

		var userreg = /\/user\//g;

		if (userreg.test(str)) {
			var elements = str.split('/');
			return Wo_StripParameters(elements.pop());
		}

		var attrreg = /\/attribution_link\?.*v%3D([^%&]*)(%26|&|$)/;

		if (attrreg.test(str)) {
			return str.match(attrreg)[1];
		}
	}
	 


	function Wo_StripParameters(str) {
		if (str.indexOf('?') > -1) {
			return str.split('?')[0];
		}
		return str;
	}
</script>
