<div class="list-group">
   <div class="list-group-item"><i class="fa fa-film" aria-hidden="true"></i> Movies Settings</div>
    <div class="setting-well page-margin">
      <div class="w-100" style="min-width: 600px;">     
          <ul class="nav nav-tabs text-center" role="tablist">
              <li role="presentation" class="active" style="width: 25%">
              	<a href="#movies" aria-controls="newsection" role="tab" data-toggle="tab">Movies</a>
              </li>

              <li role="presentation" style="width: 25%">
              	<a href="#new-film" aria-controls="forums" role="tab" data-toggle="tab">New</a>
              </li>
          </ul>
          <br>
          <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="movies">

		      <table class="table  table-hover table-bordered table-stripped setting-table">
		         <thead>
		            <tr>
		               <th><?php echo $wo['lang']['id'];?></th>
		               <th>Link</th>
		               <th>Name</th>
		               <th>Release</th>
		               <th><?php echo $wo['lang']['action'];?></th>
		            </tr>
		         </thead>
		         <tbody class="page-result manage-pages-list">
		               <?php 
		                foreach (Wo_GetMovies(array('limit' => 400)) as $wo['film']) {
		                  echo Wo_LoadPage('admin/movies/includes/movies-list');
		                }
		               ?>
		         </tbody>
		      </table>
     		 <span class="center-text"></span>
                  <div class="clear"></div>
              </div>
              <div role="tabpanel" class="tab-pane" id="new-film">
      			  <?php echo Wo_loadPage('admin/movies/new'); ?>
                  <div class="clear"></div>
              </div>
              <div class="clear"></div>
          </div> 
      </div>
    </div>
</div>

<?php echo Wo_LoadPage('admin/movies/includes/delete') ?>

<script>
$(function () {
  $('table').DataTable({"aoColumnDefs": [
          { 'bSortable': false, 'aTargets': [ 4 ] }
    ],
   "order": [[ 0, "desc" ]]});
});
	jQuery(document).ready(function($) {
		 var bar = $('#bar');
	    var percent = $('#percent');
	    var status = $('#status');
	    var publisher_button = $('#publisher-button');
		$("#select-f-cover").click(function(event) {
	      $("#film-cover").click()
	    });

	    $("#film-cover").change(function(event) {
	      $("#select-f-cover").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'  class='w100'>")
	    });


	    $('#new-film').ajaxForm({
	      url: Wo_Ajax_Requests_File() + '?f=new-film',
	      beforeSend: function() {
	      	var percentVal = '0%';
	        bar.width(percentVal);
	        percent.html(percentVal);
	        Wo_progressIconLoader($('#new-film').find('button'));
	      },
	      uploadProgress: function (event, position, total, percentComplete) {
           var percentVal = percentComplete + '%';
           bar.width(percentVal);
           $('#progress').slideDown(200);
           if(percentComplete > 50) {
             percent.addClass('white');
           }
           percent.html(percentVal);
         },
	      type:"POST",
	      success: function(data) {
	        scrollToTop();
	        bar.width(0);
	        percent.html('0%');
	        $('#progress').slideUp(200);
	        if (data['status'] == 200) {
	          $("#film-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	        } else if (data['message']) {
	          $("#film-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
	        Wo_progressIconLoader($('#new-film').find('button'));
	      }});

	    $(".delete-film").click(function(event) {
	    	$("#delete-film").attr('data-film-ident', $(this).attr('id')).modal('show');
	    });
	});

	function Wo_DeleteFilm(id){
    	if (!id) {
    		return false;
    	}
    	$.ajax({
    		url: Wo_Ajax_Requests_File(),
    		type: 'GET',
    		dataType: 'json',
    		data: {f: 'movies',s:'delete',id:id},
    	})
    	.done(function(data) {
    		if (data.status == 200) {
    			$("#delete-film").modal('hide');
    			$("tr[data-film-id="+id+"]").slideUp(function(){
    				$(this).remove();
    			})
    		}
    	})
    	.fail(function() {
    		console.log("Something went wrong. Try again later");
    	})
    	
    }
</script>

<style>
	#select-f-cover{
	max-height: 300px;
	overflow: hidden;
	}
	#select-f-cover img{
		max-width: 100%;
		max-height: 300px;
	}

	#select-film input{
		padding: 5px 0px;
	}

</style>