<tr class="setting-userlist <?php echo ($wo['report']['seen'] == 0) ? ' report-not-seen' : '';?> " id="ReportID_<?php echo $wo['report']['id']?>" >
   <td><?php echo $wo['report']['id']?></td>
   <td class="pointer">
      <?php echo ucfirst($wo['report']['type']); ?>
   </td>
   <td>
      <a href="<?php echo $wo['report']['reporter']['url']; ?>">
      <img src="<?php echo $wo['report']['reporter']['avatar'];?>" class="setting-avatar" alt="<?php echo $wo['report']['reporter']['avatar'];?> Profile Picture">
      <?php echo $wo['report']['reporter']['name']; ?>
      </a>
 
   </td>
   <td>
      <?php if ($wo['report']['type'] == 'post'): ?>
         <a href="<?php echo $wo['report']['story']['url']; ?>">
           <?php echo $wo['lang']['open_post'];?>
         </a>
      <?php elseif($wo['report']['type'] == 'profile'): ?>
         <a href="<?php echo $wo['report']['user']['url']; ?>">
            <?php echo $wo['report']['user']['name']; ?>
         </a>
      <?php elseif($wo['report']['type'] == 'page'): ?>
         <a href="<?php echo $wo['report']['page']['url']; ?>">
            <?php echo $wo['report']['page']['page_name']; ?>
         </a>
      <?php elseif($wo['report']['type'] == 'group'): ?>
         <a href="<?php echo $wo['report']['group']['url']; ?>">
            <?php echo $wo['report']['group']['group_name']; ?>
         </a>
      <?php endif; ?>
   </td>
   <td>
      <div class=" ajax-time" title="<?php echo date('c',$wo['report']['time']); ?>">
         <?php echo Wo_Time_Elapsed_String($wo['report']['time']);?>
      </div>
   </td>
   <td>
      <span class="mark-safe pointer" onclick="Wo_MarkSafeReportedPost(<?php echo $wo['report']['id']?>);">
      <i class="fa fa-check progress-icon" data-icon="check"></i> <?php echo $wo['lang']['mark_safe'];?>
      </span>|
      <?php if ($wo['report']['type'] == 'post'): ?>
         <span class="delete-report pointer" onclick="Wo_DeleteReportedContent(<?php echo $wo['report']['story']['id']?>,<?php echo $wo['report']['id']?>,'post');">
         <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> 
         Delete
         </span>
      <?php elseif($wo['report']['type'] == 'profile'): ?>
      <span class="delete-report pointer" onclick="Wo_DeleteReportedContent(<?php echo $wo['report']['user']['id']?>,<?php echo $wo['report']['id']?>,'user');">
         <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> 
         Delete
      </span>
      |
      <span class="pointer" style="font-size: 12px;" onclick="$('#read_report').modal().find('.report_text').text('<?php echo htmlspecialchars($wo['report']['text']); ?>')"><i class="fa fa-file-text-o"></i> View</span> 
      <?php elseif($wo['report']['type'] == 'page'): ?>
         <span class="delete-report pointer" onclick="Wo_DeleteReportedContent(<?php echo $wo['report']['page']['page_id']?>,<?php echo $wo['report']['id']?>,'page');">
         <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> 
         Delete
         </span>
         |
         <span class="pointer" style="font-size: 12px;" onclick="$('#read_report').modal().find('.report_text').text('<?php echo htmlspecialchars($wo['report']['text']); ?>')"><i class="fa fa-file-text-o"></i> View</span> 
      <?php elseif($wo['report']['type'] == 'group'): ?>
         <span class="delete-report pointer" onclick="Wo_DeleteReportedContent(<?php echo $wo['report']['group']['id']?>,<?php echo $wo['report']['id']?>,'group');">
         <i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> 
         Delete
         </span>
         |
          <span class="pointer" style="font-size: 12px;" onclick="$('#read_report').modal().find('.report_text').text('<?php echo htmlspecialchars($wo['report']['text']); ?>')"><i class="fa fa-file-text-o"></i> View</span> 
      
      <?php endif; ?>
   </td>
</tr>