<div class="col-md-12" >
<div id="posts">
    <?php
    $array = array('limit' => 10);
    if (!empty($_GET['user_id'])) {
        $array['publisher_id'] = Wo_Secure($_GET['user_id']);
    }
            $stories = Wo_GetPosts($array);
            if (count($stories) <= 0) {
              echo Wo_LoadPage('story/no-stories');
            } else {
              foreach ($stories as $wo['story']) {
                echo Wo_LoadPage('story/content');
              }
            }
            ?>
            </div>
             <?php if (count($stories) > 0) { ?>
         <div class="load-more pointer" id="load-more-posts" onclick="Wo_GetMorePosts();">
            <span class="btn btn-default">
            <i class="fa fa-chevron-circle-down progress-icon" data-icon="chevron-circle-down"></i> <?php echo $wo['lang']['load_more_posts'];?><span>
         </div>
         <?php } ?>
         <!-- .load-more pointer -->
         <div id="load-more-filter">
            <span class="filter-by-more hidden" data-filter-by="all"></span>
         </div>
         <!-- #load-more-filter -->

</div>