
<?php echo Wo_LoadPage("movies/includes/header"); ?>



<div class="list-group">
	

	<div class="col-md-12 col-sm-12 col-xs-12">
		<div>
			<ul class="breadcrumb movies-top-breadcrumb hidden-xs">
			    <li><i class="fa fa-home"></i>
			    <a href="<?php echo $wo['site_url']; ?>"><?php echo $wo['config']['siteName'] ?></a>
			    </li>
			    <li> <a href="<?php echo Wo_SeoLink('index.php?link1=movies') ?>"><?php echo $wo['lang']['movies']; ?></a></li>
			    <li><?php echo $wo['lang']['genre']; ?></li>
			    <li class="main"><?php echo $wo['genre']; ?></li>
			</ul>
			<div class="clear"></div>
		</div>
			
		<div class="movies">

			
			<div class="w100 movies-inner">
				<?php if (count($wo['movies']) > 0): ?>
					<?php foreach ($wo['movies'] as $wo['film']): ?>
						<?php echo Wo_LoadPage("movies/includes/films-list"); ?>
					<?php endforeach; ?>
				<?php else: ?>
					<?php echo '<h5 class="search-filter-center-text"> '. $wo['lang']['no_movies_found'] .' </h5>';?>
				<?php endif; ?>
			</div>

		

			<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
			 	<div class="posts_load">
				    <?php if (count($wo['movies']) > 26): ?>
					<div class="load-more">
	                    <button class="btn btn-default text-center pointer load-more-movies" data-genre="<?php echo strtolower($wo['genre']); ?>" data-movies-type="genre">
	                    <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more'] ?></button>
	                </div>
	                <?php endif ?>
				</div>
			</div>
		
		</div>
	</div>
	

</div>

<?php echo Wo_LoadPage("movies/includes/footer"); ?>