<?php if ($wo['loggedin'] == true) { ?>
	<?php
	$fullname="";
	$fullname=$wo['user']['first_name'].' '.$wo['user']['last_name'];
	if(empty($fullname) || $fullname==" ")
		$fullname="Unnamed";
	if(strlen($fullname)>10)
		$fullname=substr($fullname,0,10).'...';
	?>
	 <label for="toggle-1" class="toggle-menu"><ul><li></li> <li></li> <li></li></ul></label>
	 <input type="checkbox" id="toggle-1" class="toggle-1">
<div class="left-sidebar sidebar-sticky">
      <style>
               
.toggle-menu ul{display:table; width:25px;padding: 0;margin: 0;}
.toggle-menu ul li{width: 28px;height: 2px;background-color: #fff;margin-bottom: 4px;}
.toggle-menu ul li:last-child{margin-bottom:0px;}

.toggle-1,.toggle-menu{display:none;}

@media only screen and (max-width: 980px) {
.toggle-1 {display:block;position: absolute; top: -9999px; left: -9999px; background:none;}
.toggle-1:fous{background:none;}
.toggle-menu {float:left;margin-top: -15px;background-color:#333;padding: 5px;display:block; cursor:pointer; }
.toggle-1:checked ~ .left-sidebar {display:block;}

.col-md-7{ padding-top: 14px;}
.left-sidebar{margin-top: 9px;display:none; position:absolute;  background-color:#333; padding:0px; z-index:99;}
.left-sidebar ul{width:auto;}
.left-sidebar ul li{float:none; padding:0px; width:100%; display:table;}
.left-sidebar ul li a{color:#FFF; font-size:15px; padding:10px 20px; display:block; border-bottom: 1px solid rgba(225,225,225,0.1);}
.left-sidebar ul li a i{color:#fde428; padding-right:13px;}
}




            </style>
           
	<ul>
		<li><a href="<?php echo $wo['user']['url']; ?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('user-3'); ?>" alt="user-3"><?php echo $fullname;?></a></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=messages'); ?>" ><img class="sidebar-icon" src="<?php echo Wo_GetIcon('paper-plane-1'); ?>" alt="paper-plane"><?php echo $wo['lang']['messages'];?></a></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=setting'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('settings-4'); ?>" alt="settings"><?php echo $wo['lang']['setting'];?></a></li>
		<li><hr></li>
		<?php if (Wo_CanBlog() == true) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>" ><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('notebook-2'); ?>" alt="notebook-3"><?php echo $wo['lang']['my_articles'] ?></a></li>
		<?php } ?>
		<?php if ($wo['config']['groups'] == 1) { ?><li><a href="<?php echo Wo_SeoLink('index.php?link1=groups'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('users-1'); ?>" alt="users-1"><?php echo $wo['lang']['groups'];?></a></li><?php } ?>
		<?php if ($wo['config']['pages'] == 1) { ?><li><a href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('flag-2'); ?>" alt="flag-2"><?php echo $wo['lang']['pages'];?></a></li><?php } ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" ><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('picture-2'); ?>" alt="picture-2"><?php echo $wo['lang']['albums'];?></a></li>
		<?php if ($wo['config']['classified'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>" ><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('shopping-cart'); ?>" alt="shopping-cart"><?php echo $wo['lang']['my_products'];?></a></li>
		<?php } ?>
        <li><hr></li>
		<?php if ($wo['config']['games'] == 1) { ?><li><a href="<?php echo Wo_SeoLink('index.php?link1=games'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('app'); ?>" alt="app"><?php echo $wo['lang']['games'];?></a></li><?php } ?>
		<li><hr></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=saved-posts');?>" ><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('medal'); ?>" alt="medal"><?php echo $wo['lang']['saved_posts'];?></a></li>
        <li><a href="<?php echo Wo_SeoLink('index.php?link1=search?query=');?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('placeholder'); ?>" alt="placeholder">Find Friends</a></li>
		<?php if ($wo['config']['blogs'] == 1) { ?>
		<li><hr></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('document'); ?>" alt="document"><?php echo $wo['lang']['blog'] ?></a></li>
		<?php } ?>
        <?php if ($wo['config']['events'] == 1) { ?>
		<li>
			<a href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('calendar'); ?>" alt="calendar"><?php echo $wo['lang']['events'] ?></a>
		</li>
		<?php } ?>
		<?php if ($wo['config']['forum'] == 1) { ?>
		<li><hr></li>

		<li><a href="<?php echo Wo_SeoLink('index.php?link1=forum'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('chatting'); ?>" alt="chatting"><?php echo $wo['lang']['forum'];?></a></li>
		<?php } ?>
		<?php if ($wo['config']['classified'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('store'); ?>" alt="store"><?php echo $wo['lang']['market'];?></a></li>
		<?php } ?>
		<?php if ($wo['config']['movies'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=movies'); ?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('video-player-1'); ?>" alt="video-player-1"><?php echo $wo['lang']['movies'];?></a></li>
		<?php } ?>

		<?php if ($wo['config']['find_friends'] == 1) { ?>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby'); ?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('search'); ?>" alt="search"><?php echo $wo['lang']['explore'];?></a></li>
		<?php } ?>
			
		<li><a href="https://mitrah.in/index.php?link1=feedback"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('flag-2'); ?>" alt="search">Feedback<?php //echo $wo['lang']['feedback'];?></a></li>
		

		<?php if ($wo['user']['is_pro'] == 0 && $wo['config']['pro'] == 1) { ?>
		<li><hr></li>
		<li><a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>"><i class="fa fa-arrow-down fa-fw"></i><?php echo $wo['lang']['put_me_here'];?></a></li>
		<?php } ?>
	</ul>
	<?php if ($wo['config']['pro'] == 1) { ?>
      <div class="featured-users">
        <ul class="list-inline">
          <?php 
          $users = Wo_FeaturedUsers(9);
          ?>
          <?php 
          foreach ($users as $wo['user-list']) {
              echo Wo_LoadPage('home/user-list');
          }
          ?>
        </ul>
      </div><br>
      <?php } ?>
</div>
<?php } ?>
