<div class="story-video">
	<div class="video-js-responsive-container vjs-hd">
		<video class="video-js vjs-big-play-centered" controls preload="auto" poster="" data-setup="{}" width="100">
		    <source src="<?php echo $wo['media']['filename'];?>" type='video/mp4'>
		    <source src="<?php echo $wo['media']['filename'];?>" type='video/webm'> 
		</video>
	</div>
	<div class="clear"></div>
	 <script src="<?php echo $wo['config']['theme_url'];?>/player/Video/video.js"></script>
</div>