<div class="chat-wrapper chat_group_<?php echo $wo['chat']['group']['group_id'];?>">
   <div class="online-toggle pointer">
      <span class="chat-tab-status" onclick="javascript:$('.group-tab-container-<?php echo $wo['chat']['group']['group_id'];?>').slideToggle(100)";><i class="fa fa-users" aria-hidden="true"></i> <?php echo mb_substr($wo['chat']['group']['group_name'], 0, 20, "UTF-8");?>
      </span>
        <span class="dropdown <?php echo Wo_RightToLeft('pull-right');?>"  style="margin-right: 10px;">
          <i class="fa fa-caret-down dropdown-toggl" data-toggle="dropdown" onclick=""></i>
          <ul class="dropdown-menu group_tab_dropdown">
            <li onclick="Wo_CloseChat(<?php echo $wo['chat']['group']['group_id'];?>,'group')">
                <span><?php echo $wo['lang']['close']; ?></span>
            </li>
            <li onclick="Wo_ManageGChat();">
              <span><?php echo $wo['lang']['members']; ?></span>
            </li>
            <?php if ($wo['chat']['group']['user_id'] != $wo['user']['id']): ?>
              <li onclick="Wo_ExitGroupChat('<?php echo $wo['chat']['group']['group_id'];?>');">
                <span>
                   <?php echo $wo['lang']['exit_group']; ?>
                </span>
              </li>
            <?php endif; ?>
            <?php if ($wo['chat']['group']['user_id'] == $wo['user']['id']): ?>
              <li onclick="Wo_ClearGroupHistory(<?php echo $wo['chat']['group']['group_id'];?>)">
                <span><?php echo $wo['lang']['clear_history']; ?></span>
              </li>
              <li onclick="Wo_DeleteGroupChat(<?php echo $wo['chat']['group']['group_id'];?>)">
                <span><?php echo $wo['lang']['delete_group'];?></span>
              </li>
            <?php endif ?>
            
            
          </ul>
        </span>
   </div>

   <div class="chat-tab-container group-tab-container-<?php echo $wo['chat']['group']['group_id'];?> chat-tab-box-<?php echo $wo['chat']['group']['group_id'];?>">
      <div class="chat-messages-wrapper group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>">
         <div class="chat-messages">
          <?php if (count($wo['chat']['group']['messages']) > 0): ?>
            <?php foreach ($wo['chat']['group']['messages'] as $wo['chatMessage']): ?>
              <?php echo Wo_LoadPage('chat/group-chat-list'); ?>
            <?php endforeach; ?>
          <?php else: ?>
            <p class="no_message" id="no_messages_<?php echo $wo['chat']['group']['group_id'];?>">
              <?php echo $wo['lang']['no_messages']; ?>
            </p>
          <?php endif; ?>
          
         </div>

         <div class="clear"></div>
      </div>
      <div class="chat-textarea btn-group">
         <div class="emo-container emo-group-container-<?php echo $wo['chat']['group']['group_id'];?>">
            <?php  
            foreach ($wo['emo'] as $code => $name) {
              $code   = $code;
              echo  '<span onclick="Wo_AddEmoToGroup(\'' . $code . '\', ' . $wo['chat']['group']['group_id'] . ');"><i class="pointer twa-lg twa twa-' . $name . '"></i></span>'; 
            } 
            ?>
         </div>



         <form action="#" id="hren" class="group-chat-sending-<?php echo $wo['chat']['group']['group_id'];?>">
            <textarea name="textSendMessage" id="sendMessage" class="form-control" cols="10" rows="5" placeholder="<?php echo $wo['lang']['write_something'];?>"  onkeydown="Wo_SubmitChatGroupForm(event, <?php echo $wo['chat']['group']['group_id'];?>);" dir="auto" ></textarea>

            <div class="w-10 chat-btns-w" style="padding: 2px 10px;">
            <span>
              <span class="btn btn-file" id="progressIcon" style="padding: 3px;">
              <?php if($wo['config']['fileSharing'] == 1) { ?>
              <i class="fa fa-file-text-o progress-icon" data-icon="file-text-o"></i>
              <input type="file" id="sendMessasgeFile" name="sendMessageFile" class="pointer" onchange="Wo_SubmitChatGroupForm(event,<?php echo $wo['chat']['group']['group_id'];?>)" />
              <?php } else { ?>
              <i class="fa fa-picture-o  progress-icon" data-icon="picture-o"></i>
              <input type="file" id="sendMessasgeFile" name="sendMessageFile" onchange="Wo_SubmitChatGroupForm(event,<?php echo $wo['chat']['group']['group_id'];?>);" accept="image/x-png, image/gif, image/jpeg"  />
              <?php } ?>
              </span>
            </span>

            <span class="emo-btn-<?php echo $wo['chat']['group']['group_id'];?>" style="<?php echo Wo_RightToLeft('right');?>:60px;">
              <span class="btn btn-file" style="padding: 3px;">
                 <i class="fa fa-smile-o progress-icon" data-icon="file-smile-o"></i>
              </span>
            </span>


            </div>
         </form>
      </div>
   </div>
</div>



<script type="text/javascript">
  jQuery(document).ready(function($) {
    $('[data-toggle="tooltip"]').tooltip(); 
    var main_hash_id = $('.main_session').val();
    $('.emo-btn-<?php echo $wo['chat']['group']['group_id'];?>').click(function () {
        $('.emo-group-container-<?php echo $wo['chat']['group']['group_id'];?>').toggle();
    });

    $(".clear_group_chat_<?php echo $wo['chat']['group']['group_id'];?>").click(function(event) {
      event.stopPropagation();
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'chat',s:'clear_group_chat',id:'<?php echo $wo['chat']['group']['group_id'];?>'},
      })
      .done(function(data) {
        if (data.status == 200) {
          $(".group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>").empty();
        }
      })
      .fail(function() {
        console.log("error");
    });
      
    });

    var chat_messages_wrapper = $('.group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>');
    chat_messages_wrapper.scrollTop(chat_messages_wrapper[0].scrollHeight);
    $('.group-chat-sending-<?php echo $wo['chat']['group']['group_id'];?>').ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=chat&s=send_message&group_id=<?php echo $wo['chat']['group']['group_id'];?>&hash=' + main_hash_id,
        type:"POST",
        uploadProgress: function() {
          Wo_progressIconLoader($('.group-chat-sending-<?php echo $wo['chat']['group']['group_id'];?>').find('#progressIcon'));
        },
        success: function(data) {
            if (data.status == 200) {

              if ($('#no_messages_<?php echo $wo['chat']['group']['group_id'];?>').length > 0) {
                $(".group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>").find('.chat-messages').html(data.html);
              }
              else{
                $(".group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>").find('.chat-messages').append(data.html);
              }
              if (data.invalid_file == 1) {
                  $("#invalid_file").modal('show');
                  Wo_Delay(function(){
                    $("#invalid_file").modal('hide');
                  },3000);
                  
              }
              if (data.invalid_file == 2) {
                  $("#file_not_supported").modal('show');
                  Wo_Delay(function(){
                    $("#file_not_supported").modal('hide');
                  },3000);
              }
              if (data.file == true) {
                Wo_progressIconLoader($('.group-chat-sending-<?php echo $wo['chat']['group']['group_id'];?>').find('#progressIcon'));
              }
              
            }
            else if(data.status == 500 && data.invalid_file == 1){
              $("#invalid_file").modal('show');
                  Wo_Delay(function(){
                    $("#invalid_file").modal('hide');
              },3000);
              Wo_progressIconLoader($('.group-chat-sending-<?php echo $wo['chat']['group']['group_id'];?>').find('#progressIcon'));
            }
            else if(data.status == 500 && data.invalid_file == 2){
              $("#file_not_supported").modal('show');
                  Wo_Delay(function(){
                    $("#file_not_supported").modal('hide');
              },3000);
              Wo_progressIconLoader($('.group-chat-sending-<?php echo $wo['chat']['group']['group_id'];?>').find('#progressIcon'));
            }
            $(".chat_group_<?php echo $wo['chat']['group']['group_id'];?>").find('#sendMessasgeFile').val('');
            $(".chat_group_<?php echo $wo['chat']['group']['group_id'];?>").find('textarea').val('');
            setTimeout(function() {
                  chat_messages_wrapper.scrollTop(chat_messages_wrapper[0].scrollHeight);
            }, 100);

        }

    });

    setInterval(function(){
      var last_group_message = ($("[data-group-tmessage-id]").length > 0) ? $("[data-group-tmessage-id]").last().attr('data-group-tmessage-id') : 0;
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'chat',s:'get_new_group_messages',message_id:last_group_message,group_id:'<?php echo $wo['chat']['group']['group_id'];?>'},
      })
      .done(function(data) {
        if (data.status == 200) {
          if ($(".group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>").find('.no_message').length > 0) {
            $(".group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>").find('.chat-messages').html(data.html);
          }else{
            $(".group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>").find('.chat-messages').append(data.html);
          }
          
          chat_messages_wrapper.scrollTop(chat_messages_wrapper[0].scrollHeight);
        }
      })
      .fail(function() {
        console.log("error");
      })
    },5000);

  });

  function Wo_SubmitChatGroupForm(e, id) {
    document.title = document_title;
    chat_tab_container = $('.chat_main_' + id);
    if (e.keyCode == 13 && e.shiftKey == 0 || $("#sendMessasgeFile").val() != '') {
        e.preventDefault();
        $('.group-chat-sending-<?php echo $wo['chat']['group']['group_id'];?>').submit();
    }
  }

 function Wo_ClearGroupHistory(id = false){
    if (!id) { return false;}
    $.ajax({
      url: Wo_Ajax_Requests_File(),
      type: 'GET',
      dataType: 'json',
      data: {f: 'chat',s:'clear_group_chat',group_id:'<?php echo $wo['chat']['group']['group_id'];?>'},
    })
    .done(function(data) {
      if (data.status == 200) {
        $(".group-messages-wrapper-<?php echo $wo['chat']['group']['group_id'];?>")
        .find('.chat-messages')
        .html(
          '\
            <p class="no_message" id="no_messages_<?php echo $wo['chat']['group']['group_id'];?>">\
            <?php echo $wo['lang']['conversation_deleted']; ?>\
            </p>'
          );
      }
    })
    .fail(function() {
      console.log("error");
    })
  }
  function Wo_DeleteGroupChat(id = false){
    if (!id) {return false}
    $.ajax({
      url: Wo_Ajax_Requests_File(),
      type: 'GET',
      dataType: 'json',
      data: {f: 'chat',s:'delete_group_chat',group_id:'<?php echo $wo['chat']['group']['group_id'];?>'},
    })
   .done(function(data) {
      if (data.status == 200) {
        $('.chat_main_0').toggle(100,function(){
          $(this).remove();
          $("#group_tab_<?php echo $wo['chat']['group']['group_id'];?>").slideUp(function(){
            $(this).remove();
          })
        });
      }
    })
    .fail(function() {
      console.log("error");
    })
  }
  function Wo_ExitGroupChat(id = false){
    if (!id) {return false}
    $.ajax({
      url: Wo_Ajax_Requests_File(),
      type: 'GET',
      dataType: 'json',
      data: {f: 'chat',s:'exit_group_chat',group_id:'<?php echo $wo['chat']['group']['group_id'];?>'},
    })
   .done(function(data) {
      if (data.status == 200) {
        $('.chat_main_0').toggle(100,function(){
          $(this).remove();
          $("#group_tab_<?php echo $wo['chat']['group']['group_id'];?>").slideUp(function(){
            $(this).remove();
          })
        });
      }
    })
    .fail(function() {
      console.log("error");
    })
  }

  function Wo_ManageGChat(){
    $.ajax({
      url: Wo_Ajax_Requests_File(),
      type: 'GET',
      dataType: 'json',
      data: {f: 'chat',s:'group_parts',group_id:'<?php echo $wo['chat']['group']['group_id'];?>'},
    })
    .done(function(data) {
      if (data.status == 200) {
        $('#manage_group_chat').find('.modal-body').html(data.parts);
        $('#manage_group_chat').find('#group_chat_mbrs').html(data.count);
        $('#manage_group_chat').modal('show');
      }
    })
    .fail(function() {
      console.log("error");
    })
  }

</script>
