<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.woff") format("woff");
    font-weight: normal;
}
 @font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.woff") format("woff");
    font-weight: normal;
}
 .navbar-default {
    background: <?php echo $wo['config']['header_background'];?>; border: none;
    height:45px;
 }
.group-messages-wrapper a{
  color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
 .result-bar{
    background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
 }
 .avtive {border-color: <?php echo $wo['config']['btn_background_color'];?> !important;}
 #bar_loading {
    background-color: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
 }
 .left-sidebar ul li a i {color: <?php echo $wo['config']['btn_background_color'];?> !important;}
 .cs-loader-inner,  .main  {
  color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 #search-nearby-users .nearby-users-gender-collapse ul li.active {
   border-left: 3px solid <?php echo $wo['config']['btn_background_color'];?>;
 }
  .login input:focus {
    border-color: <?php echo $wo['config']['btn_background_color'];?> !important;
  }
  .login:not(.loading) button:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?>;
  }
  body .mfp-wrap .mfp-progress-line span{
  background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
  .login button {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?> !important;
  }
 .mejs-controls .mejs-time-rail .mejs-time-current, 
 .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current,
 .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    background-image: <?php echo $wo['config']['btn_background_color'];?> !important;
 }
 .navbar-default .navbar-nav>.open>a,
 .navbar-default .navbar-nav>.open>a:focus,
 .navbar-default .navbar-nav>.open>a:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
 }
 .navbar-default .navbar-nav>.active>a,
 .navbar-default .navbar-nav>.active>a:focus,
 .navbar-default .navbar-nav>.active>a:hover,
 .nav-names li:hover {
   color: <?php echo $wo['config']['header_color'];?> !important;
   background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
 }
 body {
   background-color: <?php echo $wo['config']['body_background'];?> !important;
 }
 .navbar-default .navbar-nav>li>a {
    color: <?php echo $wo['config']['header_color'];?>;
    font-size: 13px;
 }
 a.unread-update {
    color: <?php echo $wo['config']['header_color'];?> !important;
 }
 .btn-main {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .btn-main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 .admin-panel .col-md-9 .list-group-item:first-child, 
 .setting-panel .col-md-8 .list-group-item:first-child, 
 .profile-lists .list-group-item:first-child, 
 .col-md-8 .list-group-item:first-child,
.col-md-3.custom .list-group-item:first-child,
 .col-sm-4 .list-group-item:first-child,
 .col-md-7 .list-group-item:first-child,
.col-md-9 .list-group-item:first-child,
 .red-list .list-group-item:first-child,
 .active.list-group-item:first-child {
     color: #444;
     background-color: #fcfcfc;
     border-bottom: 1px solid #f1f1f1;
     padding: 18px;
 }
 .admin-panel .col-md-9 .list-group-item:first-child a, 
 .setting-panel .col-md-8 .list-group-item:first-child a, 
 .profile-lists .list-group-item:first-child a, 
 .col-md-8 .list-group-item:first-child a,
 .col-md-7 .list-group-item:first-child a,
 .active.list-group-item:first-child a {
    color: #444 !important;
 }
 .list-group-item.black-list.active-list, .red-list.active-list {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .list-group-item.black-list {
     background: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .profile-top-line {
     background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 #bar {
     background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .list-group-item.black-list a{
     color: <?php echo $wo['config']['btn_color'];?>;
 }
 .list-group-item.black-list.active-list a{
     color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .main-color, .small-text a {
     color: <?php echo $wo['config']['btn_background_color'];?> !important;
 }
 .search-advanced-container a:hover {
    text-decoration: none;
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .nav-tabs>li.active>a,
 .nav-tabs>li.active>a:focus,
 .nav-tabs>li.active>a:hover {
    color: <?php echo $wo['config']['btn_color'];?>;
    cursor: default;
    color: <?php echo $wo['config']['btn_background_color'];?>;
    border-bottom: 1px solid <?php echo $wo['config']['btn_background_color'];?>;
    background-color: transparent
 }
 .btn-active {
    color: <?php echo $wo['config']['btn_color'];?>;
    background: <?php echo $wo['config']['btn_background_color'];?>;
    outline: none;
    border: 1px solid <?php echo $wo['config']['btn_background_color'];?>
 }
 .btn-active:hover, .btn-active:focus {
    border: 1px solid <?php echo $wo['config']['btn_hover_background_color'];?>;
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 .btn-active-color:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 .chat-container {
    background: <?php echo $wo['config']['body_background'];?> !important;
 }
 .chat-tab .online-toggle {
    background: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .profile-style .user-follow-button button.btn-active,
 .btn-login,
 .btn-register {
    background: <?php echo $wo['config']['btn_background_color'];?>;
    color: <?php echo $wo['config']['btn_color'];?>;
 }
 .profile-style .user-follow-button button.btn-active:hover,
 .btn-login:hover,
 .btn-login:focus,
 .btn-register:hover,
 .btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
 }
 button:disabled  {
    background-color: <?php echo $wo['config']['btn_disabled'];?> !important;
 }
 .panel-login>.panel-heading a.active {
    color: <?php echo $wo['config']['btn_background_color'];?>;
    font-size: 18px;
 }
 .hash {
    color: <?php echo $wo['config']['btn_background_color'];?>;
 }
 .message-text .hash {
  color: #fff !important;
 }
 .sixteen-font-size {
    color: rgba(200, 200, 200, 0.5) !important;
    text-shadow: 0 1px 1px <?php echo $wo['config']['header_button_shadow'];?>;
   -webkit-text-shadow: 0 1px 1px <?php echo $wo['config']['header_button_shadow'];?>;
   -moz-text-shadow: 0 1px 1px <?php echo $wo['config']['header_button_shadow'];?>;
   -o-text-shadow: 0 1px 1px <?php echo $wo['config']['header_button_shadow'];?>;
 }
 .search-container .search-input {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background: <?php echo $wo['config']['header_search_color'];?> !important;
 }
 .chat-messages-wrapper .outgoing {
     background: <?php echo $wo['config']['chat_outgoing_background'];?>;
 }
 .normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
.post-privacy-menu li a:hover, .post-privacy-menu li div:hover {
  color: <?php echo $wo['config']['btn_color'];?>;
  background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.active.fa-thumbs-up {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.post-privacy-menu li a:hover, .post-privacy-menu li div:hover { background-color: <?php echo $wo['config']['btn_background_color'];?>; color: <?php echo $wo['config']['btn_color'];?>; }
.api-ex-urls, .movies-navbar-wrapper, .movies-navbar-wrapper .dropdown, .movies-navbar-wrapper .dropdown a.dropdown-toggle {
    background-color: <?php echo $wo['config']['btn_background_color'];?>; color: <?php echo $wo['config']['btn_color'];?>;
}
.user-username {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.upload-image {
    border: 3px dashed <?php echo $wo['config']['btn_background_color'];?>;
}
.events-tab-list li { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.events-tab-list li:hover { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.active-e-tab { background-color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.main { color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.events-list-dropup-menu ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?>; }
.products .product .product-links .more-info, .usr-offline { color: <?php echo $wo['config']['btn_background_color'];?>; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?> !important; }
.blog_publ {background: <?php echo $wo['config']['btn_background_color'];?> ; border: 1px solid <?php echo $wo['config']['btn_background_color'];?> ; }


.ads-navbar-wrapper {
  background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.slide-film-desc:hover, .movies-top-breadcrumb li:hover, .movies-top-breadcrumb li a:hover{
  color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.movies h3.latest-movies, h3.recommended-movies {
  border-left: 3px solid  <?php echo $wo['config']['btn_background_color'];?>;
}

.movies-search input {
  background: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
  color: <?php echo $wo['config']['btn_color'];?> !important;
}
</style>