<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
 <?php echo Wo_LoadPage('welcome/welcome-header-logo');?>
  <form class="login" id="forgot-form" method="post">
    <p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
    <input name="recoveremail" id="recoveremail" type="text" placeholder="Phone Number" autofocus/><i class="fa fa-phone"></i>
     <button id="state1">
    <i class="spinner"></i>
    <span class="state"><i class="fa fa-repeat"></i> <?php echo $wo['lang']['recover_password'];?></span>
    </button>
  </form>
  <form class="login" id="otp" method="post" style="display:none;">
  <i class="fa fa-key"></i>
    <input name="register_otp" id="register_otp" type="text" placeholder="<?php echo 'Enter OTP sent on your phone';?>" />
    <button onclick="return getnewpass();">
    <i class="spinner"></i>
    <span class="state"><i class="fa fa-repeat"></i>Let's Go</span>
    </button>
    </form>
    <form class="login" id="Update-form" method="post" style="display:none;">
    <p class="title">Get New Password</p>
    <input name="newpass" id="newpass" type="password" placeholder="Enter New Password" value="" autofocus/>
    <input name="confirmpass" id="confirmpass" type="password" placeholder="Enter Confirm Password" value="" autofocus/>
     <button id="st" onclick="return updatepass();">
    <i class="spinner"></i>
    <span class="state"><i class="fa fa-repeat"></i> Update Password</span>
    </button>
  </form>
  <?php echo Wo_LoadPage('footer/welcome');?>
</div>
<?php echo Wo_LoadPage('welcome/welcome-users-profiles');?>
<script>
var working = false;
 var recoveremail="";
var $this = $('#forgot-form');
var $state = $this.find('button  .state');
var forgot_button_text = "<i class='fa fa-repeat'></i> <?php echo $wo['lang']['recover_password']?>";
$(function() {
    $('#state1').on('click', function(e) {
         recoveremail=$("#recoveremail").val();
    //if(recoveremail=="") {
      //  alert("Please enter Phone Number");
    //} 
    //else {
        //alert("sent");
          Wo_SetTimer();
          $this.ajaxForm({
            url: 'forgot-code.php',
            beforeSend: function() {
              working = true;
              $this.addClass('loading');
              $state.html('<?php echo $wo['lang']['please_wait'] ?>');
            },
            success: function(data) {
          
              if (data == 'success') {
               console.log(data);
                $this.addClass('ok');
                $state.html('<?php echo "OTP is sent on your number" ?>');
                setTimeout(function () {
                  $this.removeClass('ok loading');
                  //$state.html(forgot_button_text);
                }, 5000);
                $("#otp").show();
                $("#forgot-form").hide();
                
              } else if(data == 'error'){
                setTimeout(function () {
                  $this.removeClass('ok loading');
                  $state.html('<?php echo "Please enter valid phone number." ?>');
                }, 5000);
                
              }
              else {
                console.log('Something went wrong!');
                $state.html(forgot_button_text);
                $this.removeClass('ok loading', function () {
                 $state.html(data.errors);
                });
              }
              working = false;
            }
  });
   // }
    });
    

});

function getnewpass(){
    var otp=$("#register_otp").val();

        var $this = $('#otp');
        var $state = $this.find('button > .state');
        var forgot_button_text = "<i class='fa fa-repeat'></i>Lestsgo";
        //var $state = $this.find('button > .state');
         Wo_SetTimer();
          $this.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=otpCode',
            beforeSend: function() {
              working = true;
              $this.addClass('loading');
              $state.html('<?php //echo $wo['lang']['please_wait'] ?>');
            },
            success: function(data) {
            
              if (data.status == 200) {
                  //alert(data.html); 
                $this.addClass('ok');
                $state.html('<?php echo "OTP Verified" ?>');
                $("#Update-form").show();
                
                $("#otp").hide();
                setTimeout(function () {
                  $this.removeClass('ok loading');
                 $state.html(forgot_button_text);
                }, 5000);

                $("#forgot-form").hide();
                
               } else {
                  
                 $state.html(forgot_button_text);
                 $this.removeClass('ok loading', function () {
                   $state.html(data.errors);
                });
               }
              working = false;
             
            }
  });

                //$("#Update-form").show();
        // $("#otp").hide();
                
     
     
}

function updatepass(){
    var newpass=$("#newpass").val();
        var $this = $('#Update-form');
        var $state = $this.find('button > .state');
        var forgot_button_text = "<i class='fa fa-repeat'></i>Update Password";
        //var $state = $this.find('button > .state');
         Wo_SetTimer();
          $this.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=upass&phno='+recoveremail,
            beforeSend: function() {
              working = true;
              $this.addClass('loading');
              $state.html('<?php //echo $wo['lang']['please_wait'] ?>');
            },
            success: function(data) {
              if (data.status == 200) {
                 $("#otp").hide();
                $this.addClass('ok');
                $state.html('<?php echo "Password Updated..Please Login to continue.." ?>');
                //$("#Update-form").show();
                
                //setTimeout(function () {
                  //$this.removeClass('ok loading');
                 //$state.html(forgot_button_text);
               // }, 5000);
                //$("#otp").show();
                //$("#forgot-form").hide();
                
              } else {
                $state.html(forgot_button_text);
                $this.removeClass('ok loading', function () {
                    $state.html(data.errors);
                });
              }
              working = false;
               recoveremail="";
               
            }
  });

                //$("#Update-form").show();
        // $("#otp").hide();
                
     
     
}
</script>
