<?php echo Wo_LoadPage('welcome/welcome-header');?>
<div class="wrapper">
 <?php echo Wo_LoadPage('welcome/welcome-header-logo');?>
  <form class="login" id="forgot-form" method="post">
    <p class="title"><?php echo $wo['lang']['forgot_your_password']; ?></p>
    <input name="recoveremail" id="recoveremail" type="text" placeholder="<?php echo $wo['lang']['phone_number'];?>" autofocus/>
    <i class="fa fa-phone"></i>
    
    <input type="submit" id="state" value="Recover"/>
    
  </form>
  
 
      
  <button style="display:none" class="statec"  style="background: #a84849 !important;
color: #ffffff !important;width: 100%;padding: 10px 10px;">
    <i class="spinner"></i>
    <span><i class="fa fa-repeat"></i>Click Here to get OTP</span>
    </button>
    
  
    
    
  <form class="login" id="verify-form" method="post" style="display:none;">
  <i class="fa fa-key"></i>
    <input name="otp" id="register_otp" type="text" placeholder="<?php echo 'Enter OTP sent on your phone';?>" />
    <i class="fa fa-key"></i>
    
    </form>
  <?php echo Wo_LoadPage('footer/welcome');?>
</div>
<?php echo Wo_LoadPage('welcome/welcome-users-profiles');?>
<script>
var working = false;
var $this = $('#otp-form');
var $state = $this.find('button > .state1');
var forgot_button_text = "<i class='fa fa-repeat'></i>Click Here to get OTP";



$(function() {
    $('#state').on('click', function(e) {
        var recoveremail=$("#recoveremail").val();
    if(recoveremail=="") {
        alert("Please enter Phone Number");
       
    } else {
    $(".statec").show();
     
     
   
    }
  });
  
  
  
  
});
</script>
