<?php echo Wo_LoadPage('ads/includes/header'); ?>
<div class="w100 create-ads-cont">
	<form  class="form" method="get" id="create-ads">
	<div class="col-md-7 col-lg-7 col-sm-7 col-xs-12 create-ads-inner-left">
		<div id="create-ads-alert" class="w100">
			
		</div>
		<div class="form-group w100">
			<label class="col-md-3 col-sm-12 col-xs-12"><?php echo $wo['lang']['company']; ?>:</label>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<input type="text" class="form-control" name="name" max="50">
			</div>
		</div>
		<div>
			<div class="col-md-3 col-sm-12 col-xs-12"></div>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<small class="main"><?php echo $wo['lang']['select_a_page_or_link'] ?></small>
			</div>
		</div>
		<div class="form-group w100">
			
			<label class="col-md-3 col-sm-12 col-xs-12"><?php echo $wo['lang']['url']; ?>:</label>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<input type="url" class="form-control" name="website">
			</div>
		</div>
		<div class="form-group w100">
			
			<label class="col-md-3 col-sm-12 col-xs-12"><?php echo $wo['lang']['my_pages']; ?>:</label>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<select class="form-control" name="page" id="select-page">			
				<?php if ($wo['my-pages'] && count($wo['my-pages']) > 0): ?>
					<option value="" selected>
						<?php echo $wo['lang']['select']; ?>
					</option>
					<?php foreach ($wo['my-pages'] as $wo['pageItem']): ?>
						<option value="<?php echo $wo['pageItem']['page_name']; ?>">
							<?php echo $wo['pageItem']['page_name']; ?>
						</option>
					<?php endforeach; ?>
				<?php else:?>
					<option disabled="disabled" selected="selected">
							<?php echo $wo['lang']['no_pages_found']; ?>
					</option>
				<?php endif;?>
				</select>
			</div>
		</div>
		<div class="form-group w100">
			
			<label class="col-md-3 col-sm-12 col-xs-12"><?php echo $wo['lang']['title']; ?>:</label>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<input type="text" class="form-control" name="headline">
			</div>
		</div>

		<div class="form-group w100">
			
			<label class="col-md-3 col-sm-12 col-xs-12"><?php echo $wo['lang']['description']; ?>:</label>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<textarea class="form-control" name="description"></textarea>
			</div>
		</div>


		<div class="form-group w100">
			
			<label class="col-md-3 col-sm-12 col-xs-12"><?php echo $wo['lang']['location']; ?>:</label>
			<div class="col-md-9 col-sm-12 col-xs-12" id="review-ads-location">
				<input id="ads-location" name="location"  type="text" class="form-control"> 
			</div>
		</div>
		<div class="form-group w100" id="review-ads-location">
          <div class="col-sm-3"></div>
          <div class="col-md-9" id="place"> 
          </div>
       </div>
       	<div class="form-group w100">
			<label class="col-md-3"><?php echo $wo['lang']['audience']; ?></label>
			<div class="col-md-9">
				<div class="form-control ads-audience" >
					<?php foreach ($wo['audience'] as $country_ids => $country): ?>
						<p>
							<input 
							type="checkbox" 
							class="ads-audience-list" 
							name="audience-list[]" 
							value="<?php echo $country_ids; ?>"
							<?php if ($country_ids == 0) {
								echo "id='select-all-countries'";
							}?>
							style="vertical-align: middle;"
							>
							<label style="vertical-align: middle;"><?php echo $country; ?></label>
						</p>
					<?php endforeach;?>
				</div>
			</div>
		</div>
		<div class="form-group w100">
			<label class="col-md-3"></label>
			<div class="col-md-9">
				<button class="btn btn-main pull-right" type="submit" <?php echo ($wo['user']['wallet'] == '0.00' || $wo['user']['wallet'] == '0') ? 'disabled' : ''; ?>>
					<i class="fa fa-plus-square progress-icon fa-fw"></i>
					<?php echo $wo['lang']['add']; ?>
				</button>
				<button class="btn btn-default pull-right cancel" type="reset">
					<i class="fa fa-ban progress-icon fa-fw"></i>
					<?php echo $wo['lang']['cancel']; ?>
				</button>
			</div>
		</div>	
	</div>
	<div class="col-md-5 col-sm-5 col-lg-5 col-xs-12 create-ads-inner-right">
		<div class="form-group w100">
			<div class="col-md-12" id="select-ads-img" title="Select image">
				<p class="img"> <i class="fa fa-picture-o" aria-hidden="true"></i>
					<?php echo $wo['lang']['select_image']; ?>
				</p>
			</div>
		</div>
		<hr>
		<div class="form-group w100">
			<div class="col-md-12">
				<p><?php echo $wo['lang']['gender']; ?></p>
				<div>
					<input type="radio" name="gender" value="all" checked>
					<span>
						<?php echo $wo['lang']['all']; ?>
					</span>
				</div>
				<div>
					<input type="radio" name="gender" value="male">
					<span>
						<?php echo $wo['lang']['male']; ?>
					</span>
				</div>
				<div>
					<input type="radio" name="gender" value="famale">
					<span><?php echo $wo['lang']['female']; ?></span>
				</div>
				<hr>
				<p><?php echo $wo['lang']['appears'] ?></p>
				<div>
					<input type="radio" name="appears" value="post" checked>
					<span><?php echo $wo['lang']['post']; ?></span>
				</div>
				<div>
					<input type="radio" name="appears" value="sidebar">
					<span><?php echo $wo['lang']['sidebar']; ?></span>
				</div>
				<hr>
				<p><?php echo $wo['lang']['bidding']; ?></p>
				<select name="bidding" id="bidding" class="form-control">
					<option value="clicks"><?php echo str_replace('{{PRICE}}', $wo['config']['ad_c_price'], $wo['lang']['pay_per_click']); ?></option>
					<option value="views"><?php echo str_replace('{{PRICE}}', $wo['config']['ad_v_price'], $wo['lang']['pay_per_imprssion']); ?></option>
				</select>
			</div>
			
			<div class="col-md-12">
				<?php 
				if ($wo['user']['wallet'] == '0.00' || $wo['user']['wallet'] == '0') {
					?>
					<br>
					<div class="alert alert-warning">
						<?php echo $wo['lang']['balance_is_0'] ?> <a href="<?php echo Wo_SeoLink('index.php?link1=wallet'); ?>"><?php echo $wo['lang']['top_up'] ?></a>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<input type="file" name="image" class="hidden" id="ads-image" accept="image/*">
	</form>
</div>

<script>
	
	jQuery(document).ready(function($) {
	  $("#ads-location").keyup(function(event) {
        if ($(this).val().length >= 3) {
          Wo_Delay(function(){$("#review-ads-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + $("#ads-location").val() + '&language=en"></iframe>')},1000)
        }
        else{
          Wo_Delay(function(){$("#review-ads-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=us&language=en"></iframe>')},1000)
        }
      });

	  $("#select-page").change(function(event) {
	  	var self     = $(this);
	  	if (self.val() != '') {
	  		var page_url = document.location.origin +'/'+ self.val();
	  		$('#create-ads').find("input[name=website]").val(page_url);
	  	}

	  	else{
	  		$('#create-ads').find("input[name=website]").val('');
	  	}
	  	
	  });

      $("#select-all-countries").change(function(event) {
      	var self = $(this);
      	if (self.is(':checked')) {
      		$("input.ads-audience-list").each(function(index, el) {
      			$(el).prop('checked', true);
      		});
      	}
      	else{
      		$("input.ads-audience-list").each(function(index, el) {
      			$(el).prop('checked', false);
      		});
      	}
	          	
      });

      $("#select-ads-img").click(function(event) {
      	$("#ads-image").click();
      });


      $("#ads-image").change(function(event) {
      	$("#select-ads-img").html('<img src="' + window.URL.createObjectURL(this.files[0]) + '">');
      });

      $('#create-ads').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=ads&s=new',
       type:"POST",
       beforeSend: function() {
        Wo_progressIconLoader($('#create-ads').find('button.btn-main'));
       },
       success: function(data) {
        scrollToTop();
        if (data['status'] == 200) {
          $("#create-ads-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
          window.location = data.url;
        } else if (data['message']) {
          $("#create-ads-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
        } 
        Wo_progressIconLoader($('#create-ads').find('button.btn-main'));
      }});

	});
</script>
