<tr class="setting-blog"  data-film-id="<?php echo $wo['film']['id']; ?>">
   <td><?php echo $wo['film']['id']?></td>
   <td>
      <a href="<?php echo $wo['film']['url']; ?>">LINK</a>
   </td>
   <td>
      <a href="<?php echo $wo['film']['url']; ?>">
         <?php echo $wo['film']['name']; ?>
      </a>
   </td>
   <td>
     <div class="ajax-time">
         <?php echo $wo['film']['release'];?>
     </div>
   </td>
   <td>
      <span class="pointer delete-film" id="<?php echo $wo['film']['id']; ?>">
      <i class="fa fa-trash-o"></i>
      </span>
   </td>
</tr>