<div class="list-group">
  <div class="list-group-item"><i class="fa fa-fw fa-trash-o"></i> <?php echo "Deactivate Account"; ?> <?php if(Wo_IsAdmin() === true) { ?><a href="<?php echo $wo['setting']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['username'] ?>">(<?php echo $wo['setting']['name'];?>)</a><?php } ?></div>
   <div class="setting-well">
   <form action="#" method="post" class="form-horizontal setting-delete-account-form">
      <fieldset>
         <div class="setting-delete-account-alert setting-update-alert"></div>
         <div class="form-group">
            <label class="col-md-3" for="password"><?php echo "Reason"; ?></label>
            <div class="col-md-7">
               <select class="deactivate-select" name="deactivate">
                <option class="deactivate-option" value="1">This is temporary. I'll be back</option>
                <option class="deactivate-option" value="2">I don't find Mitrah useful</option>
                <option class="deactivate-option" value="3">I spend too much time using Mitrah</option>
                <option class="deactivate-option" value="4">I don't understand how to use Mitrah</option>
                <option class="deactivate-option" value="5">I have a privacy concern</option>
                <option class="deactivate-option" value="6">I have another Mitrah account</option>
                <option class="deactivate-option" value="7">I uses some other Social network website</option>
                <option class="deactivate-option" value="8">My account was hacked</option>
                <option class="deactivate-option" value="9">I don't feel safe on Mitrah</option>
                <option class="deactivate-option" value="10">I get too many emails, invitations, and requests from Mitrah</option>
                <option class="deactivate-option" value="11">Other</option>
               </select>
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3"><?php echo "Additional Comments"; ?></label>
            <div class="col-md-7">
               <textarea id="password" name="additional" class="form-control input-md"></textarea>
            </div>
         </div>
         <div class="form-group">
            <label class="col-md-3" for="password"><?php echo $wo['lang']['current_password']; ?></label>
            <div class="col-md-7">
               <input id="password" name="password" type="password" class="form-control input-md">
            </div>
         </div>
         
         <hr>
         <div class="form-group last-btn">
            <label class="col-md-3"></label>
            <div class="col-sm-3 text-left">
               <button type="submit" class="btn btn-main">
               <i class="fa fa-remove progress-icon" data-icon="remove"></i> <?php echo "Deactivate"; ?>
               </button>
            </div>
         </div>
      </fieldset>
   </form>
</div>
</div>
<script type="text/javascript">
$(function() {
  $('form.setting-delete-account-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=deactivate_user_account',
    beforeSend: function() {
      Wo_progressIconLoader($('form.setting-delete-account-form').find('button'));
    },
    success: function(data) {
      if (data.status == 200) {
        $('.setting-delete-account-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          window.setTimeout(function() {
            window.location.href = data.location;
          }, 3000);
        });
      } else {
        var errors = data.errors.join("<br>");
        $('.setting-delete-account-alert').html('<div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      Wo_progressIconLoader($('form.setting-delete-account-form').find('button'));
    }
  });
});
</script>