
<div class="list-group">
   <div class="list-group-item">
    <i class="fa fa-buysellads" aria-hidden="true"></i> Advertising
   </div>
   <div class="setting-well">
      <div class="clear"></div>
      <table class="table  table-hover table-bordered table-condensed setting-table">
         <thead>
            <tr>
               <th><?php echo $wo['lang']['id'];?></th>
               <th>Website</th>
               <th>User</th>
               <th><?php echo $wo['lang']['time'];?></th>
               <th><?php echo $wo['lang']['action'];?></th>
            </tr>
         </thead>
         <tbody class="page-result manage-pages-list" id="user-ads">
               <?php 
                $user_ads = Wo_GetAds();
                if ($user_ads && count($user_ads) > 0) {
                    foreach ($user_ads as $wo['user_ad']) {
                      echo Wo_LoadPage('admin/user_ads/ads-list');
                    }
                }
                else{
                  echo "<tr><td colspan='5' class='text-center' style='padding:100px 0;'>".$wo['lang']['no_ads_found']."</td></tr>";
                }

               ?>
         </tbody>
         

         

      </table>
      <?php if (count($user_ads) > 15): ?>
        <div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
          <div class="posts_load">
              
            <div class="load-more">
              <button class="btn btn-default text-center pointer load-more-ads">
              <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i>
              <?php echo $wo['lang']['load_more'] ?>
              </button>
            </div>
           <br>    
          </div>
        </div>
      <?php endif ?>
      <span class="center-text"></span>
   </div>
</div>
<div class="modal fade" id="delete-ad" >
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title"><i class="fa fa-exclamation-circle"></i> <?php echo $wo['lang']['delete_ad']; ?></h4>
         </div>
         <div class="modal-body">
            <p><?php echo $wo['lang']['confirm_delete_ad']; ?></p>
         </div>
         <div class="modal-footer">
            <button  type="button" onclick="Wo_DeleteAd($('#delete-ad').attr('data-ad-id'))" class="btn  btn-main"><i class="fa fa-trash-o progress-icon" data-icon="trash-o"></i> <?php echo $wo['lang']['delete']; ?></button>
            <button  type="button" class="btn btn-default" data-dismiss="modal"><?php echo $wo['lang']['cancel']; ?></button>
         </div>
      </div>
   </div>
</div>
<script>
jQuery(document).ready(function($) {
  $(".load-more-ads").click(function(event) {
      var last_ad = ($("tr[data-userad-id]").length > 0) ? $("tr[data-userad-id]").last().attr('data-userad-id') : 0;
      var self    = $(this);
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'ads',s:'alm',ad_id:last_ad},
      })
      .done(function(data) {
        if (data.status == 200) {
          $("#user-ads").append(data.html);
        }
        else if(data.status == 404){
          self.removeClass('load-more-ads').html(data.html);
        }
        else{
          self.remove();
        }
      })
      .fail(function() {
        console.log("error");
      })   
  });

  $(document).on('click', '.delete-ad', function(event) {
    var self = $(this); 
    $("#delete-ad").attr('data-ad-id',self.attr('id')).modal("show");

  });
});

function Wo_DeleteBlog(id) {
  if (confirm("Are you sure you want to delete this blog?'") == false) {
    return false;
  }
  $.get(Wo_Ajax_Requests_File(),{f:'delete-my-blog',id: id}, function(data) {
    if (data.status == 200) {
      $('#BlogID_' + id).fadeOut(300, function() {
        $(this).remove();
      });
    }
  });
}
function Wo_DeleteAd(id){
  if (id && id > 0) {
    $.ajax({
      url: Wo_Ajax_Requests_File(),
      type: 'GET',
      dataType: 'json',
      data: {f: 'wallet',s:'remove',id:id},
    })
    .done(function(data) {
      if (data.status == 200) {
        $("tr[data-userad-id="+id+"]").slideUp(function(){
          $(this).remove();
        })
        $("#delete-ad").modal("hide");
      }
    })
    .fail(function() {
      console.log("error");
    })
  }
}
</script>
