<div class="profile-style">
   <a href="<?php echo $wo['page']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['page']['page_name'];?>">
      <div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
         <img src="<?php echo $wo['page']['avatar'];?>" alt="<?php echo $wo['page']['page_name']; ?> Profile Picture" />
      </div>
      <?php echo $wo['page']['page_title']; ?>
   </a>
   <div class="page-website"></div>
</div>