<div class="panel panel-white more-option-container">
    <ul class="additional-options">
        <li class="more_option_begin">
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=groups');?>" ><?php echo $wo['lang']['groups'];?></a>
        </li>
        <li >
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=likes');?>"><?php echo $wo['lang']['likes'];?></a>
        </li>
        <li>
            <a href="<?php echo Wo_SeoLink('index.php?link1=albums&user=' . $wo['user_profile']['username']);?>"><?php echo $wo['lang']['albums'];?></a>
        </li>
        <li >
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=followers');?>" ><?php echo $wo['lang']['friends_btn'];?> </a>
        </li>
        <li >
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=movies');?>" ><?php echo "Movies";?></a>
        </li>
        <li >
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=sports');?>"><?php echo "Sports";?></a>
        </li>
        <li >
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=tv');?>"><?php echo "TV Shows";?></a>
        </li>
        <li >
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=books');?>" ><?php echo "Books";?></a>
        </li>
        <li >
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=health');?>" ><?php echo "Health";?></a>
        </li>
        <li class="more_option_end">
            <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=music');?>" ><?php echo "Music";?></a>
        </li>
    </ul>
</div>