<div class="sidebar-ad-wrapper pointer rads-<?php echo $wo['sidebar-ad']['bidding']; ?>" id="<?php echo $wo['sidebar-ad']['id']; ?>">
    <div class="sidebar-ad-header">
        <h4><i class="fa fa-bullhorn"></i>&nbsp; <?php echo $wo['lang']['sponsored'] ?></h4>
    </div>
    <hr>
    <div class="sidebar-ad-body">
        <img src="<?php echo $wo['sidebar-ad']['image']; ?>" alt="Picture">
    </div>
    <div class="sidebar-ad-footer">
        <p class="ad-title">
            <?php echo $wo['sidebar-ad']['headline']; ?>
        </p>
        <p class="small ad-descrition ">
            <?php echo $wo['sidebar-ad']['description']; ?>
        </p>
        <time>
            <a href="<?php  echo $wo['sidebar-ad']['url'];?>" class="main" target="_blank">
                <?php echo Wo_UrlDomain($wo['sidebar-ad']['url']); ?>
            </a>
        </time>
    </div>
</div>